language: ruby
rvm:
  - '2.1.4'
env:
  - DB=postgresql
before_install:
  - mv ./config/database.yml.sample ./config/database.yml
before_script:
  - psql -c 'create database curem_test' -U postgres
script:
  - bundle exec rake --trace db:migrate RAILS_ENV=test
  - bundle exec rspec spec
notifications:
  email: false